#!/usr/bin/env bash
# VayuVeer Cloud GCS — one-file Raspberry Pi 5 installer.
# Copy this file to the Pi, double-click it, choose "Execute in Terminal".
# It downloads the software, installs dependencies, enables the flight-controller
# serial port, writes the config, installs the auto-start service and offers to reboot.
set -u

# Pre-fillable defaults (the pre-filled copy handed to operators has the token set).
SERVER_URL="${VAYUVEER_SERVER_URL:-wss://gcs.vayuveer.in}"
TOKEN="${VAYUVEER_TOKEN:-__TOKEN__}"
DRONE_ID="${VAYUVEER_DRONE_ID:-vayuveer-01}"
REPO="https://github.com/airotorac/vayuveer-cloud-gcs.git"
DEST="$HOME/vayuveer-cloud-gcs"

# Re-launch inside a terminal window when started by double-click without one.
if [ ! -t 0 ]; then
  for term in lxterminal x-terminal-emulator xterm; do
    if command -v "$term" >/dev/null 2>&1; then exec "$term" -e "bash '$0'"; fi
  done
fi

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
step() { echo; bold "==> $*"; }
fail() { echo; bold "ERROR: $*"; echo "Press Enter to close."; read -r; exit 1; }

echo
bold "VayuVeer Cloud GCS — Raspberry Pi installer"
echo "Relay: $SERVER_URL"
echo

PLACEHOLDER="__TOK""EN__"   # split so the pre-fill step only touches the default above
if [ -z "$TOKEN" ] || [ "$TOKEN" = "$PLACEHOLDER" ]; then
  read -r -p "Access token (from the administrator): " TOKEN
  [ -n "$TOKEN" ] || fail "a token is required"
fi
read -r -p "Aircraft ID [$DRONE_ID]: " ans; DRONE_ID="${ans:-$DRONE_ID}"

CAM="picamera2"
read -r -p "Camera: 1 = Pi camera module (CSI), 2 = USB camera, 3 = none / simulated [1]: " ans
case "${ans:-1}" in 2) CAM="opencv";; 3) CAM="mock";; esac

step "Installing packages"
sudo apt-get update -qq || fail "apt-get update failed (is the Pi online?)"
sudo apt-get install -y -qq git python3-venv python3-picamera2 python3-opencv >/dev/null || fail "package install failed"

step "Getting the software"
if [ -d "$DEST/.git" ]; then
  git -C "$DEST" pull -q || fail "git pull failed"
else
  git clone -q "$REPO" "$DEST" || fail "git clone failed"
fi
cd "$DEST" || fail "cannot enter $DEST"
[ -d .venv ] || python3 -m venv --system-site-packages .venv
.venv/bin/pip install -q -r drone/requirements.txt || fail "pip install failed"

step "Enabling the flight-controller serial port"
CFG=/boot/firmware/config.txt
grep -q "^enable_uart=1" "$CFG" || echo "enable_uart=1" | sudo tee -a "$CFG" >/dev/null
grep -q "^dtparam=uart0=on" "$CFG" || echo "dtparam=uart0=on" | sudo tee -a "$CFG" >/dev/null
sudo sed -i 's/console=serial0,115200 //; s/console=ttyAMA0,115200 //' /boot/firmware/cmdline.txt
sudo usermod -aG dialout,video "$USER"
CONN="/dev/serial0"; [ -e /dev/ttyACM0 ] && CONN="/dev/ttyACM0"

step "Writing drone/config.yaml"
cat > drone/config.yaml <<CFGEOF
# VayuVeer Cloud GCS — companion agent configuration (generated by the installer)
server_url: $SERVER_URL
token: $TOKEN
drone_id: $DRONE_ID
telemetry_hz: 5

drone:
  mode: mavlink
  connection: $CONN
  baud: 921600
  mock_home_lat: 23.0225
  mock_home_lon: 72.5714

camera:
  enabled: true
  source: $CAM
  device: /dev/video0
  width: 1280
  height: 720
  fps: 10
  quality: 65

manual:
  max_speed_mps: 5.0
  max_climb_mps: 2.0
  max_yaw_rate_dps: 60
  max_age_s: 0.6

failsafe:
  action: rtl
  link_loss_s: 10

safety:
  require_arm_confirm: true
  default_takeoff_alt: 10
  max_alt: 120
CFGEOF
chmod 600 drone/config.yaml

step "Installing the auto-start service"
sed -e "s|User=pi|User=$USER|" -e "s|/home/pi/vayuveer-cloud-gcs|$DEST|g" drone/vayuveer-agent.service \
  | sudo tee /etc/systemd/system/vayuveer-agent.service >/dev/null
sudo systemctl daemon-reload && sudo systemctl enable -q vayuveer-agent

echo
bold "Done. Aircraft '$DRONE_ID' will connect to $SERVER_URL on every boot."
echo "FC port: $CONN   Camera: $CAM   Config: $DEST/drone/config.yaml"
echo "After reboot, watch it with:  journalctl -fu vayuveer-agent"
echo
read -r -p "Reboot now to finish? [Y/n] " ans
case "${ans:-Y}" in
  [Yy]*) sudo reboot;;
  *) echo "Reboot later with: sudo reboot"; read -r -p "Press Enter to close." _;;
esac
